services:
- type: web
  name: hackerdaily-backend
  env: docker
  autoDeploy: true
  healthCheckPath: /healthz
  envVars:
  - key: PORT
    value: 10000
  - key: HASURA_GRAPHQL_DATABASE_URL
    fromDatabase:
      name: hackerdaily-database
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: HASURA_GRAPHQL_ADMIN_SECRET
    generateValue: true
databases:
- name: hackerdaily-database
